In [41]:
"""
What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.
"""

'\nWhat is PyTorch?\n================\n\nIt’s a Python-based scientific computing package targeted at two sets of\naudiences:\n\n-  A replacement for NumPy to use the power of GPUs\n-  a deep learning research platform that provides maximum flexibility\n   and speed\n\nGetting Started\n---------------\n\nTensors\n^^^^^^^\n\nTensors are similar to NumPy’s ndarrays, with the addition being that\nTensors can also be used on a GPU to accelerate computing.\n'

In [0]:
from __future__ import print_function
import torch

In [43]:
x = torch.empty(5, 3)
print(x)

tensor([[ 5.2514e-36,  0.0000e+00,  4.4842e-44],
        [ 0.0000e+00,         nan,  2.3416e-01],
        [ 6.5647e-07,  2.1953e-04,  2.6221e-09],
        [ 3.3211e-09,  5.3534e+22,  4.3916e-05],
        [ 8.3963e-07,  1.0682e-05, -3.8112e-01]])


In [44]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5236, 0.5546, 0.9636],
        [0.4088, 0.8813, 0.3651],
        [0.5243, 0.7486, 0.1404],
        [0.2872, 0.5602, 0.5238],
        [0.3841, 0.9576, 0.3799]])


In [45]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [46]:
#  Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [47]:
# create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [48]:
# override the dtype
x = torch.randn_like(x, dtype= torch.float)
print(x)

tensor([[-0.4093, -0.1106,  0.8712],
        [ 1.5170,  1.2946, -1.4419],
        [-1.9879, -0.0655, -0.4401],
        [ 0.5574, -0.6939, -0.2785],
        [-0.3420,  0.7216, -1.0032]])


In [49]:
print(x.size())

torch.Size([5, 3])


In [50]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.0620, -0.0838,  1.7563],
        [ 2.3148,  1.9011, -1.3241],
        [-1.5700,  0.7746,  0.0381],
        [ 0.9134,  0.2803,  0.1391],
        [ 0.2668,  0.8323, -0.6618]])


In [51]:
print(torch.add(x, y))

tensor([[ 0.0620, -0.0838,  1.7563],
        [ 2.3148,  1.9011, -1.3241],
        [-1.5700,  0.7746,  0.0381],
        [ 0.9134,  0.2803,  0.1391],
        [ 0.2668,  0.8323, -0.6618]])


In [52]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)  # result is the tensor

tensor([[ 0.0620, -0.0838,  1.7563],
        [ 2.3148,  1.9011, -1.3241],
        [-1.5700,  0.7746,  0.0381],
        [ 0.9134,  0.2803,  0.1391],
        [ 0.2668,  0.8323, -0.6618]])


In [53]:
# .. note::
#     Any operation that mutates a tensor in-place is post-fixed with an ``_``.
#     For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.
y.add_(x)
print(y)

tensor([[ 0.0620, -0.0838,  1.7563],
        [ 2.3148,  1.9011, -1.3241],
        [-1.5700,  0.7746,  0.0381],
        [ 0.9134,  0.2803,  0.1391],
        [ 0.2668,  0.8323, -0.6618]])


In [54]:
help(torch.randn)

Help on built-in function randn:

randn(...)
    randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with random numbers from a normal distribution
    with mean `0` and variance `1` (also called the standard normal
    distribution).
    
    .. math::
        \text{out}_{i} \sim \mathcal{N}(0, 1)
    
    The shape of the tensor is defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            De

In [55]:
# Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [57]:
# If you have a one element tensor, use ``.item()`` to get the value as a
# Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4921])
-0.49213922023773193


In [59]:
# NumPy Bridge
# ------------
#
# Converting a Torch Tensor to a NumPy array and vice versa is a breeze.
#
# The Torch Tensor and NumPy array will share their underlying memory
# locations (if the Torch Tensor is on CPU), and changing one will change
# the other.
#
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [61]:
# See how changing the np array changed the Torch Tensor automatically
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [63]:
# Tensors can be moved onto any device using the ``.to`` method. Except for some chartensor

# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
  print("1")
  device = torch.device("cuda")
  y = torch.ones_like(x, device= device)
  x = x.to(device)
  z = x+y
  print(z)
  print(z.to("cpu", torch.double))# ``.to`` can also change dtype together!

1
tensor([0.5079], device='cuda:0')
tensor([0.5079], dtype=torch.float64)
